
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 18;
  public static final int OR = 19;
  public static final int RO = 10;
  public static final int NOT = 20;
  public static final int TRUE = 21;
  public static final int QUOTEDS = 6;
  public static final int WITH = 15;
  public static final int PV = 8;
  public static final int RC = 11;
  public static final int COMMA = 9;
  public static final int SO = 12;
  public static final int EOF = 0;
  public static final int CMP = 14;
  public static final int TOK3 = 5;
  public static final int FZ_AND = 17;
  public static final int TOK2 = 4;
  public static final int FALSE = 22;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int PRINT = 16;
  public static final int error = 1;
  public static final int EQ = 23;
  public static final int SC = 13;
  public static final int VAR = 7;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "QUOTEDS",
  "VAR",
  "PV",
  "COMMA",
  "RO",
  "RC",
  "SO",
  "SC",
  "CMP",
  "WITH",
  "PRINT",
  "FZ_AND",
  "AND",
  "OR",
  "NOT",
  "TRUE",
  "FALSE",
  "EQ"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[18]=new String("AND");
		TT[19]=new String("OR");
		TT[10]=new String("RO");
		TT[20]=new String("NOT");
		TT[21]=new String("TRUE");
		TT[6]=new String("QUOTEDS");
		TT[15]=new String("WITH");
		TT[8]=new String("PV");
		TT[11]=new String("RC");
		TT[9]=new String("COMMA");
		TT[12]=new String("SO");
		TT[0]=new String("EOF");
		TT[14]=new String("CMP");
		TT[5]=new String("TOK3");
		TT[17]=new String("FZ_AND");
		TT[4]=new String("TOK2");
		TT[22]=new String("FALSE");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[16]=new String("PRINT");
		TT[1]=new String("error");
		TT[23]=new String("EQ");
		TT[13]=new String("SC");
		TT[7]=new String("VAR");
	}
public String getTT(int i){return TT[i];}
}

