/* The following code was generated by JFlex 1.7.0 */

import java_cup.runtime.*;


/**
 * This class is a scanner generated by 
 * <a href="http://www.jflex.de/">JFlex</a> 1.7.0
 * from the specification file <tt>./scanner.jflex</tt>
 */
class scanner implements java_cup.runtime.Scanner {

  /** This character denotes the end of file */
  public static final int YYEOF = -1;

  /** initial size of the lookahead buffer */
  private static final int ZZ_BUFFERSIZE = 16384;

  /** lexical states */
  public static final int YYINITIAL = 0;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = { 
     0, 0
  };

  /** 
   * Translates characters to character classes
   */
  private static final String ZZ_CMAP_PACKED = 
    "\11\0\1\3\1\1\1\30\1\30\1\2\22\0\1\3\1\10\1\6"+
    "\1\0\1\24\3\0\1\45\1\46\1\31\1\7\1\44\1\12\1\47"+
    "\1\25\1\4\1\13\1\14\1\15\1\17\1\20\1\21\1\26\1\5"+
    "\1\16\1\27\1\34\1\32\1\0\1\33\1\11\1\0\1\64\2\0"+
    "\1\70\1\62\1\63\2\0\1\54\2\0\1\65\1\0\1\66\1\67"+
    "\2\0\1\60\1\55\1\57\1\61\11\0\1\56\1\0\1\36\1\43"+
    "\1\0\1\41\1\40\3\0\1\22\1\23\2\0\1\37\1\35\1\42"+
    "\1\51\1\50\1\52\1\0\1\53\20\0\1\30\u1fa2\0\1\30\1\30"+
    "\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\uffff\0\udfe6\0";

  /** 
   * Translates characters to character classes
   */
  private static final char [] ZZ_CMAP = zzUnpackCMap(ZZ_CMAP_PACKED);

  /** 
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\1\0\1\1\2\2\2\3\3\1\1\4\7\1\1\5"+
    "\1\6\1\7\1\10\5\1\1\0\1\11\7\0\1\12"+
    "\3\0\1\2\11\0\1\13\12\0\1\14\2\0\1\15"+
    "\4\0\1\16\1\17\2\0\1\20\1\21\1\22\5\0"+
    "\1\23\2\0\1\24\10\0\1\25\14\0\1\26\5\0"+
    "\1\27\15\0\1\30\13\0";

  private static int [] zzUnpackAction() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** 
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\71\0\162\0\71\0\71\0\253\0\344\0\u011d"+
    "\0\u0156\0\u018f\0\u01c8\0\u0201\0\u023a\0\u0273\0\u02ac\0\u02e5"+
    "\0\u031e\0\71\0\71\0\71\0\71\0\u0357\0\u0390\0\u03c9"+
    "\0\u0402\0\u043b\0\344\0\71\0\u0474\0\u04ad\0\u04e6\0\u051f"+
    "\0\u0558\0\u0591\0\u05ca\0\71\0\u0603\0\u063c\0\u0675\0\u06ae"+
    "\0\u06e7\0\u0720\0\u0759\0\u0792\0\u07cb\0\u0804\0\u083d\0\u0876"+
    "\0\u08af\0\71\0\u08e8\0\u0921\0\u095a\0\u0993\0\u09cc\0\u0a05"+
    "\0\u0a3e\0\u0a77\0\u0ab0\0\u0ae9\0\71\0\u0b22\0\u0b5b\0\71"+
    "\0\u0b94\0\u0bcd\0\u0c06\0\u0c3f\0\71\0\71\0\u0c78\0\u0cb1"+
    "\0\71\0\71\0\u08e8\0\u0cea\0\u0d23\0\u0d5c\0\u0d95\0\u0dce"+
    "\0\71\0\u0e07\0\u0e40\0\71\0\u0e79\0\u0eb2\0\u0eeb\0\u0f24"+
    "\0\u0f5d\0\u0f96\0\u0fcf\0\u1008\0\71\0\u1041\0\u107a\0\u10b3"+
    "\0\u10ec\0\u1125\0\u115e\0\u1197\0\u11d0\0\u1209\0\u1242\0\u127b"+
    "\0\u12b4\0\71\0\u12ed\0\u1326\0\u135f\0\u1398\0\u13d1\0\71"+
    "\0\u140a\0\u1443\0\u147c\0\u14b5\0\u14ee\0\u1527\0\u1560\0\u1599"+
    "\0\u15d2\0\u160b\0\u1644\0\u167d\0\u16b6\0\71\0\u16ef\0\u1728"+
    "\0\u1761\0\u179a\0\u17d3\0\u180c\0\u1845\0\u187e\0\u18b7\0\u18f0"+
    "\0\u1929";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /** 
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpackTrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\2\1\3\2\4\1\5\1\6\1\7\1\10\1\11"+
    "\1\12\1\13\7\6\2\2\1\14\1\15\1\6\1\2"+
    "\1\0\1\2\1\16\2\2\1\17\2\2\1\20\1\2"+
    "\1\21\1\2\1\22\1\23\1\24\1\25\1\2\1\26"+
    "\2\2\1\27\7\2\1\30\1\2\1\31\1\32\1\2"+
    "\73\0\1\4\72\0\2\6\5\0\7\6\4\0\1\6"+
    "\42\0\6\33\1\34\62\33\7\0\1\35\74\0\1\36"+
    "\62\0\1\37\4\0\1\40\1\41\1\42\2\43\1\37"+
    "\1\43\1\37\4\0\1\43\53\0\1\44\23\0\1\45"+
    "\2\0\1\46\44\0\1\47\101\0\1\50\3\0\1\51"+
    "\46\0\1\52\117\0\1\53\67\0\1\54\76\0\1\55"+
    "\77\0\1\56\73\0\1\57\101\0\1\60\71\0\1\61"+
    "\61\0\1\62\17\0\1\63\65\0\1\64\6\0\1\65"+
    "\61\0\2\66\5\0\7\66\4\0\1\66\47\0\1\66"+
    "\5\0\1\67\1\66\2\70\1\66\1\70\1\66\4\0"+
    "\1\70\45\0\1\71\2\72\5\0\7\72\1\73\1\74"+
    "\2\0\1\72\5\0\1\75\40\0\1\72\1\66\5\0"+
    "\3\72\1\66\1\72\1\76\1\66\4\0\1\66\45\0"+
    "\1\71\2\66\5\0\7\66\1\73\1\74\2\0\1\66"+
    "\5\0\1\75\74\0\1\77\100\0\1\100\24\0\1\101"+
    "\64\0\1\50\2\0\25\50\1\0\40\50\31\51\1\102"+
    "\37\51\7\0\1\103\120\0\1\104\72\0\1\105\52\0"+
    "\1\106\67\0\1\107\124\0\1\110\102\0\1\111\57\0"+
    "\1\112\20\0\1\113\65\0\1\65\6\0\1\114\61\0"+
    "\1\115\6\0\1\115\70\0\1\116\1\0\2\116\1\0"+
    "\1\116\5\0\1\116\45\0\1\71\1\66\6\0\1\70"+
    "\1\117\2\116\1\0\1\116\1\0\1\73\1\74\2\0"+
    "\1\116\5\0\1\75\37\0\1\71\7\0\1\116\1\0"+
    "\2\116\1\0\1\116\1\0\1\73\1\74\2\0\1\116"+
    "\5\0\1\75\37\0\1\71\30\0\1\75\40\0\2\66"+
    "\5\0\1\70\1\66\2\70\1\66\1\70\1\66\4\0"+
    "\1\70\45\0\1\71\17\0\1\74\10\0\1\75\37\0"+
    "\1\71\16\0\1\73\11\0\1\75\40\0\1\66\6\0"+
    "\1\70\1\66\1\70\1\116\1\66\1\70\1\120\4\0"+
    "\1\116\112\0\1\121\34\0\1\122\54\0\25\51\1\4"+
    "\3\51\1\102\37\51\7\103\1\123\61\103\40\0\1\124"+
    "\65\0\1\125\112\0\1\126\3\0\1\127\10\0\1\71"+
    "\1\130\6\0\1\130\20\0\1\75\37\0\1\71\1\131"+
    "\6\0\1\131\20\0\1\75\37\0\1\71\16\0\1\73"+
    "\1\74\10\0\1\75\47\0\1\116\1\0\1\116\57\0"+
    "\1\116\6\0\3\116\1\0\2\116\70\0\1\132\1\133"+
    "\47\0\7\103\1\134\61\103\53\0\1\135\75\0\1\136"+
    "\74\0\1\137\7\0\1\71\1\140\6\0\1\140\20\0"+
    "\1\75\37\0\1\71\1\141\6\0\1\141\20\0\1\75"+
    "\61\0\1\142\70\0\1\143\43\0\7\103\1\134\23\103"+
    "\1\4\35\103\61\0\1\144\74\0\1\145\6\0\1\71"+
    "\1\146\6\0\1\146\20\0\1\75\37\0\2\71\6\0"+
    "\1\71\20\0\1\75\40\0\1\147\6\0\1\150\61\0"+
    "\1\151\146\0\1\152\63\0\1\153\16\0\2\71\27\0"+
    "\1\75\41\0\1\154\5\0\1\154\2\0\1\155\2\0"+
    "\1\156\4\0\1\154\46\0\1\154\6\0\1\155\1\154"+
    "\67\0\1\154\1\157\136\0\1\160\33\0\1\161\70\0"+
    "\1\162\70\0\1\163\70\0\1\164\47\0\1\165\6\0"+
    "\2\166\1\167\57\0\1\165\6\0\2\166\1\170\67\0"+
    "\1\171\1\170\57\0\1\165\6\0\1\166\1\172\61\0"+
    "\1\173\5\0\7\173\4\0\1\173\46\0\2\173\5\0"+
    "\7\173\4\0\1\173\46\0\1\173\6\0\1\173\61\0"+
    "\1\173\71\0\1\173\10\0\4\173\4\0\1\173\46\0"+
    "\1\173\6\0\3\173\1\0\1\173\54\0\1\174\23\0"+
    "\1\175\4\0\1\176\37\0\1\174\30\0\1\176\40\0"+
    "\1\177\6\0\1\200\62\0\1\201\10\0\1\201\1\0"+
    "\1\202\1\201\4\0\1\201\46\0\1\203\113\0\1\204"+
    "\70\0\1\205\70\0\1\206\45\0\1\207\6\0\3\207"+
    "\1\0\2\207\63\0\1\210\2\207\1\0\2\207\54\0"+
    "\1\207\6\0\3\207\1\0\1\211\55\0\2\174\5\0"+
    "\7\174\4\0\1\174\47\0\1\174\10\0\1\174\56\0"+
    "\1\174\6\0\3\174\1\0\3\174\4\0\1\174\42\0";

  private static int [] zzUnpackTrans() {
    int [] result = new int[6498];
    int offset = 0;
    offset = zzUnpackTrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackTrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /* error codes */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  private static final int ZZ_NO_MATCH = 1;
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /* error messages for the codes above */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state <code>aState</code>
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\1\0\1\11\1\1\2\11\14\1\4\11\5\1\1\0"+
    "\1\11\7\0\1\11\3\0\1\1\11\0\1\11\12\0"+
    "\1\11\2\0\1\11\4\0\2\11\2\0\2\11\1\1"+
    "\5\0\1\11\2\0\1\11\10\0\1\11\14\0\1\11"+
    "\5\0\1\11\15\0\1\11\13\0";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[137];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** the input device */
  private java.io.Reader zzReader;

  /** the current state of the DFA */
  private int zzState;

  /** the current lexical state */
  private int zzLexicalState = YYINITIAL;

  /** this buffer contains the current text to be matched and is
      the source of the yytext() string */
  private char zzBuffer[] = new char[ZZ_BUFFERSIZE];

  /** the textposition at the last accepting state */
  private int zzMarkedPos;

  /** the current text position in the buffer */
  private int zzCurrentPos;

  /** startRead marks the beginning of the yytext() string in the buffer */
  private int zzStartRead;

  /** endRead marks the last character in the buffer, that has been read
      from input */
  private int zzEndRead;

  /** number of newlines encountered up to the start of the matched text */
  private int yyline;

  /** the number of characters up to the start of the matched text */
  private int yychar;

  /**
   * the number of characters from the last newline up to the start of the 
   * matched text
   */
  private int yycolumn;

  /** 
   * zzAtBOL == true iff the scanner is currently at the beginning of a line
   */
  private boolean zzAtBOL = true;

  /** zzAtEOF == true iff the scanner is at the EOF */
  private boolean zzAtEOF;

  /** denotes if the user-EOF-code has already been executed */
  private boolean zzEOFDone;
  
  /** 
   * The number of occupied positions in zzBuffer beyond zzEndRead.
   * When a lead/high surrogate has been read from the input stream
   * into the final zzBuffer position, this will have a value of 1;
   * otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /* user code: */
    private Symbol sym(int type) {
        return new Symbol(type, yyline, yycolumn);
    }
    private Symbol sym(int type, Object value) {
        return new Symbol(type, yyline, yycolumn, value);
    }


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  scanner(java.io.Reader in) {
    this.zzReader = in;
  }


  /** 
   * Unpacks the compressed character translation table.
   *
   * @param packed   the packed character translation table
   * @return         the unpacked character translation table
   */
  private static char [] zzUnpackCMap(String packed) {
    char [] map = new char[0x110000];
    int i = 0;  /* index in packed string  */
    int j = 0;  /* index in unpacked array */
    while (i < 194) {
      int  count = packed.charAt(i++);
      char value = packed.charAt(i++);
      do map[j++] = value; while (--count > 0);
    }
    return map;
  }


  /**
   * Refills the input buffer.
   *
   * @return      <code>false</code>, iff there was new input.
   * 
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead-zzStartRead);

      /* translate stored positions */
      zzEndRead-= zzStartRead;
      zzCurrentPos-= zzStartRead;
      zzMarkedPos-= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate) {
      /* if not: blow it up */
      char newBuffer[] = new char[zzBuffer.length*2];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      throw new java.io.IOException("Reader returned 0 characters. See JFlex examples for workaround.");
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      /* If numRead == requested, we might have requested to few chars to
         encode a full Unicode character. We assume that a Reader would
         otherwise never return half characters. */
      if (numRead == requested) {
        if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }

    
  /**
   * Closes the input stream.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true;            /* indicate end of file */
    zzEndRead = zzStartRead;  /* invalidate buffer    */

    if (zzReader != null)
      zzReader.close();
  }


  /**
   * Resets the scanner to read from a new input stream.
   * Does not close the old reader.
   *
   * All internal variables are reset, the old input stream 
   * <b>cannot</b> be reused (internal buffer is discarded and lost).
   * Lexical state is set to <tt>ZZ_INITIAL</tt>.
   *
   * Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader   the new input stream 
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzAtBOL  = true;
    zzAtEOF  = false;
    zzEOFDone = false;
    zzEndRead = zzStartRead = 0;
    zzCurrentPos = zzMarkedPos = 0;
    zzFinalHighSurrogate = 0;
    yyline = yychar = yycolumn = 0;
    zzLexicalState = YYINITIAL;
    if (zzBuffer.length > ZZ_BUFFERSIZE)
      zzBuffer = new char[ZZ_BUFFERSIZE];
  }


  /**
   * Returns the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   */
  public final String yytext() {
    return new String( zzBuffer, zzStartRead, zzMarkedPos-zzStartRead );
  }


  /**
   * Returns the character at position <tt>pos</tt> from the 
   * matched text. 
   * 
   * It is equivalent to yytext().charAt(pos), but faster
   *
   * @param pos the position of the character to fetch. 
   *            A value from 0 to yylength()-1.
   *
   * @return the character at position pos
   */
  public final char yycharat(int pos) {
    return zzBuffer[zzStartRead+pos];
  }


  /**
   * Returns the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occured while scanning.
   *
   * In a wellformed scanner (no or only correct usage of 
   * yypushback(int) and a match-all fallback rule) this method 
   * will only be called with things that "Can't Possibly Happen".
   * If this method is called, something is seriously wrong
   * (e.g. a JFlex bug producing a faulty scanner etc.).
   *
   * Usual syntax/scanner level error handling should be done
   * in error fallback rules.
   *
   * @param   errorCode  the code of the errormessage to display
   */
  private void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    }
    catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  } 


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * They will be read again by then next call of the scanning method
   *
   * @param number  the number of characters to be read again.
   *                This number must not be greater than yylength()!
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }


  /**
   * Contains user EOF-code, which will be executed exactly once,
   * when the end of file is reached
   */
  private void zzDoEOF() throws java.io.IOException {
    if (!zzEOFDone) {
      zzEOFDone = true;
      yyclose();
    }
  }


  /**
   * Resumes scanning until the next regular expression is matched,
   * the end of input is encountered or an I/O-Error occurs.
   *
   * @return      the next token
   * @exception   java.io.IOException  if any I/O-Error occurs
   */
  public java_cup.runtime.Symbol next_token() throws java.io.IOException {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char [] zzBufferL = zzBuffer;
    char [] zzCMapL = ZZ_CMAP;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      boolean zzR = false;
      int zzCh;
      int zzCharCount;
      for (zzCurrentPosL = zzStartRead  ;
           zzCurrentPosL < zzMarkedPosL ;
           zzCurrentPosL += zzCharCount ) {
        zzCh = Character.codePointAt(zzBufferL, zzCurrentPosL, zzMarkedPosL);
        zzCharCount = Character.charCount(zzCh);
        switch (zzCh) {
        case '\u000B':  // fall through
        case '\u000C':  // fall through
        case '\u0085':  // fall through
        case '\u2028':  // fall through
        case '\u2029':
          yyline++;
          yycolumn = 0;
          zzR = false;
          break;
        case '\r':
          yyline++;
          yycolumn = 0;
          zzR = true;
          break;
        case '\n':
          if (zzR)
            zzR = false;
          else {
            yyline++;
            yycolumn = 0;
          }
          break;
        default:
          zzR = false;
          yycolumn += zzCharCount;
        }
      }

      if (zzR) {
        // peek one character ahead if it is \n (if we have counted one line too much)
        boolean zzPeek;
        if (zzMarkedPosL < zzEndReadL)
          zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        else if (zzAtEOF)
          zzPeek = false;
        else {
          boolean eof = zzRefill();
          zzEndReadL = zzEndRead;
          zzMarkedPosL = zzMarkedPos;
          zzBufferL = zzBuffer;
          if (eof) 
            zzPeek = false;
          else 
            zzPeek = zzBufferL[zzMarkedPosL] == '\n';
        }
        if (zzPeek) yyline--;
      }
      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;
  
      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {
    
          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMapL[zzInput] ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
            zzDoEOF();
          { return new java_cup.runtime.Symbol(sym.EOF); }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1: 
            { System.out.println("SCANNER ERROR: " + yytext());
            } 
            // fall through
          case 25: break;
          case 2: 
            { ;
            } 
            // fall through
          case 26: break;
          case 3: 
            { return sym(sym.UINT, new Integer(yytext()));
            } 
            // fall through
          case 27: break;
          case 4: 
            { return sym(sym.INTERR);
            } 
            // fall through
          case 28: break;
          case 5: 
            { return sym(sym.CM);
            } 
            // fall through
          case 29: break;
          case 6: 
            { return sym(sym.RO);
            } 
            // fall through
          case 30: break;
          case 7: 
            { return sym(sym.RC);
            } 
            // fall through
          case 31: break;
          case 8: 
            { return sym(sym.DOT);
            } 
            // fall through
          case 32: break;
          case 9: 
            { return sym(sym.QSTRING, new String(yytext()));
            } 
            // fall through
          case 33: break;
          case 10: 
            { return sym(sym.INTERR_MIN);
            } 
            // fall through
          case 34: break;
          case 11: 
            { return sym(sym.OR, new String(yytext()));
            } 
            // fall through
          case 35: break;
          case 12: 
            { return sym(sym.TOK1);
            } 
            // fall through
          case 36: break;
          case 13: 
            { return sym(sym.MIN_EQ, new String(yytext()));
            } 
            // fall through
          case 37: break;
          case 14: 
            { return sym(sym.END, new String(yytext()));
            } 
            // fall through
          case 38: break;
          case 15: 
            { return sym(sym.OBJ, new String(yytext()));
            } 
            // fall through
          case 39: break;
          case 16: 
            { return sym(sym.AND, new String(yytext()));
            } 
            // fall through
          case 40: break;
          case 17: 
            { return sym(sym.NOT, new String(yytext()));
            } 
            // fall through
          case 41: break;
          case 18: 
            { return sym(sym.SEP);
            } 
            // fall through
          case 42: break;
          case 19: 
            { return sym(sym.N_MIN_EQ, new String(yytext()));
            } 
            // fall through
          case 43: break;
          case 20: 
            { return sym(sym.NAME, new String(yytext()));
            } 
            // fall through
          case 44: break;
          case 21: 
            { return sym(sym.PRINT, new String(yytext()));
            } 
            // fall through
          case 45: break;
          case 22: 
            { return sym(sym.IS_TRUE, new String(yytext()));
            } 
            // fall through
          case 46: break;
          case 23: 
            { return sym(sym.IS_FALSE, new String(yytext()));
            } 
            // fall through
          case 47: break;
          case 24: 
            { return sym(sym.TOK2);
            } 
            // fall through
          case 48: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
