
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int AND = 20;
  public static final int N_MIN_EQ = 18;
  public static final int OR = 22;
  public static final int CM = 7;
  public static final int RO = 8;
  public static final int NOT = 21;
  public static final int MIN_EQ = 19;
  public static final int END = 13;
  public static final int IS_TRUE = 15;
  public static final int NAME = 12;
  public static final int INTERR_MIN = 6;
  public static final int IS_FALSE = 16;
  public static final int RC = 9;
  public static final int EOF = 0;
  public static final int OBJ = 14;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int PRINT = 17;
  public static final int error = 1;
  public static final int DOT = 10;
  public static final int INTERR = 5;
  public static final int UINT = 23;
  public static final int QSTRING = 11;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "INTERR",
  "INTERR_MIN",
  "CM",
  "RO",
  "RC",
  "DOT",
  "QSTRING",
  "NAME",
  "END",
  "OBJ",
  "IS_TRUE",
  "IS_FALSE",
  "PRINT",
  "N_MIN_EQ",
  "MIN_EQ",
  "AND",
  "NOT",
  "OR",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[20]=new String("AND");
		TT[18]=new String("N_MIN_EQ");
		TT[22]=new String("OR");
		TT[7]=new String("CM");
		TT[8]=new String("RO");
		TT[21]=new String("NOT");
		TT[19]=new String("MIN_EQ");
		TT[13]=new String("END");
		TT[15]=new String("IS_TRUE");
		TT[12]=new String("NAME");
		TT[6]=new String("INTERR_MIN");
		TT[16]=new String("IS_FALSE");
		TT[9]=new String("RC");
		TT[0]=new String("EOF");
		TT[14]=new String("OBJ");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[17]=new String("PRINT");
		TT[1]=new String("error");
		TT[10]=new String("DOT");
		TT[5]=new String("INTERR");
		TT[23]=new String("UINT");
		TT[11]=new String("QSTRING");
	}
public String getTT(int i){return TT[i];}
}

