
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int SEP = 2;
  public static final int TOK3 = 5;
  public static final int error = 1;
  public static final int S = 6;
  public static final int TOK2 = 4;
  public static final int TOK1 = 3;
  public static final int EOF = 0;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[2]=new String("SEP");
		TT[5]=new String("TOK3");
		TT[1]=new String("error");
		TT[6]=new String("S");
		TT[4]=new String("TOK2");
		TT[3]=new String("TOK1");
		TT[0]=new String("EOF");
	}
public String getTT(int i){return TT[i];}
}

