
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int BC = 9;
  public static final int PIPE = 14;
  public static final int CM = 15;
  public static final int S = 6;
  public static final int RO = 11;
  public static final int COL = 19;
  public static final int M = 18;
  public static final int MS = 10;
  public static final int RC = 12;
  public static final int EOF = 0;
  public static final int TOK3 = 5;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int error = 1;
  public static final int ARROW = 13;
  public static final int EQ = 7;
  public static final int BO = 8;
  public static final int UINT = 21;
  public static final int QSTRING = 20;
  public static final int PRINT_MIN_MAX = 16;
  public static final int PART = 17;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "TOK3",
  "S",
  "EQ",
  "BO",
  "BC",
  "MS",
  "RO",
  "RC",
  "ARROW",
  "PIPE",
  "CM",
  "PRINT_MIN_MAX",
  "PART",
  "M",
  "COL",
  "QSTRING",
  "UINT"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[9]=new String("BC");
		TT[14]=new String("PIPE");
		TT[15]=new String("CM");
		TT[6]=new String("S");
		TT[11]=new String("RO");
		TT[19]=new String("COL");
		TT[18]=new String("M");
		TT[10]=new String("MS");
		TT[12]=new String("RC");
		TT[0]=new String("EOF");
		TT[5]=new String("TOK3");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[1]=new String("error");
		TT[13]=new String("ARROW");
		TT[7]=new String("EQ");
		TT[8]=new String("BO");
		TT[21]=new String("UINT");
		TT[20]=new String("QSTRING");
		TT[16]=new String("PRINT_MIN_MAX");
		TT[17]=new String("PART");
	}
public String getTT(int i){return TT[i];}
}

