
//----------------------------------------------------
// The following code was generated by CUP v0.11b beta 20140226
//----------------------------------------------------

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int LOW = 15;
  public static final int PLUS = 6;
  public static final int CM = 10;
  public static final int STAR = 8;
  public static final int S = 5;
  public static final int RO = 12;
  public static final int POINT = 14;
  public static final int COL = 11;
  public static final int RC = 13;
  public static final int EOF = 0;
  public static final int DIV = 9;
  public static final int MEDIUM = 16;
  public static final int TOK2 = 4;
  public static final int SEP = 2;
  public static final int TOK1 = 3;
  public static final int MINUS = 7;
  public static final int error = 1;
  public static final int HIGH = 17;
  public static final int QSTRING = 18;
  public static final int REAL = 19;
  public static final String[] terminalNames = new String[] {
  "EOF",
  "error",
  "SEP",
  "TOK1",
  "TOK2",
  "S",
  "PLUS",
  "MINUS",
  "STAR",
  "DIV",
  "CM",
  "COL",
  "RO",
  "RC",
  "POINT",
  "LOW",
  "MEDIUM",
  "HIGH",
  "QSTRING",
  "REAL"
  };
public String[] TT;
	public sym(){
		TT = new String[100];
		TT[15]=new String("LOW");
		TT[6]=new String("PLUS");
		TT[10]=new String("CM");
		TT[8]=new String("STAR");
		TT[5]=new String("S");
		TT[12]=new String("RO");
		TT[14]=new String("POINT");
		TT[11]=new String("COL");
		TT[13]=new String("RC");
		TT[0]=new String("EOF");
		TT[9]=new String("DIV");
		TT[16]=new String("MEDIUM");
		TT[4]=new String("TOK2");
		TT[2]=new String("SEP");
		TT[3]=new String("TOK1");
		TT[7]=new String("MINUS");
		TT[1]=new String("error");
		TT[17]=new String("HIGH");
		TT[18]=new String("QSTRING");
		TT[19]=new String("REAL");
	}
public String getTT(int i){return TT[i];}
}

